version: 2
jobs:
  build:
    working_directory: ~/postgres_dba
    docker:
      - image: circleci/postgres:9.6
    steps:
      - checkout
      - run:
          name: "Prepare DB"
          command: psql -c "create database test;"
  test:
    docker:
      - image: circleci/postgres:9.6
    steps:
      - checkout
      - run:
          name: Test
          command: psql test -c "select 1;"
