version: 2
jobs:
  build:
    working_directory: ~/postgres_dba
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          - PGHOST: 127.0.0.1
          - PGUSER: root
      - image: circleci/postgres:9.6
        environment:
          - POSTGRES_USER: root
          - POSTGRES_DB: test
    steps:
      - checkout
      - run:
          name: Install psql
          command: |
            sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
            wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
            sudo apt-get update
            sudo apt install postgresql-client
      - run:
          name: Prepare DB
          command: psql test -c "create table aaa as select i from generate_series(1, 1000) _(i);"
      - run:
          name: Test
          command: psql test -c "select i from aaa limit 1;"
